version: '3.9'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/:rw
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/foodgram-backend:latest
    restart: always
    volumes:
      - static_volume:/app/static/:rw
      - media_volume:/app/media/:rw
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  frontend:
    image: ${DOCKER_USERNAME}/foodgram-frontend:latest
    volumes:
      - frontend_volume:/app/result_build/build/:rw
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - ./nginx/:/etc/nginx/templates:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
      - frontend_volume:/usr/share/nginx/html/:ro      
      - static_volume:/var/html/static/:rw
      - media_volume:/var/html/media/:rw
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - backend
      - frontend
    env_file:
      - ./.env

  certbot:
    image: certbot/certbot
    restart: unless-stopped    
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgresql_volume:
  static_volume:
  media_volume:
  frontend_volume:
  certbot_certs:
