# Generated by Django 4.1.7 on 2023-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_quantityingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuantityIngredients',
            new_name='IngredientsInRecipe',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientsinrecipe',
            name='\nrecipes_quantityingredients ingredient has already been added\n',
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='\nrecipes_ingredientsinrecipe ingredient has already been added\n'),
        ),
    ]
