# Generated by Django 4.1.7 on 2023-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('cooking_time', 0), _negated=True), name='recipes_recipe_cooking_time_not_zero'),
        ),
    ]
