# Generated by Django 4.1.7 on 2023-03-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_recipes_recipe_cooking_time_not_zero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_name is empty\n',
        ),
    ]
