# Generated by Django 4.1.7 on 2023-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_ingredient_\nrecipes_ingredient_name is empty\n'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gt', 0)), name='\nrecipes_ingredient_name is empty\n'),
        ),
    ]
